### ISSUE TITLE
Items not appended using momentum/inertia scroll on iOS

### ISSUE THREAD

**Issue by jcypret** [emberjs/ember-collection#105]
When showing scrolling through a collection on iOS, new items are not added during momentum/inertia scrolling. As soon as the finger leaves the screen/mouse/trackpad, no new items are added. I'm assuming this has to do with scroll events not being fired once the screen is not being touched. 

Is there any known fix for this issue?

**Comment by runspired** [comment]
@jcypret I'm assuming you are referring to a cordova app?

**Comment by jcypret** [comment]
@runspired Actually, yes! I'm working on a Cordova app. Do I need to configure things differently with that in mind?

**Comment by runspired** [comment]
@jcypret you need either something like `iscroll` or to upgrade to `wkWebView`

**Comment by lukemelia** [comment]
We built yapplabs/ember-virtual-scrollkit on top of ember-collection to
solve this problem in UIWebViews. It is unfortunately not well-documented
yet.

**Comment by jcypret** [comment]
@runspired @lukemelia Thanks for the recommendations! I ended up going with `wkWebView` and it worked like a charm!
