### ISSUE TITLE
how to test sort ordered collection when dom elements are not same order as visual order

### ISSUE THREAD

**Issue by danielspaniel** [emberjs/ember-collection#107]
I am curious about this one because it's kind of neat-o that ember collection uses the matrix css property to place dom elements in the visual world, but this makes testing a 'sort ordered' list .. really hard .. is it impossible? Don't know. 

Assuming each element in the ember collection kinda looks like this:
```html
<div style="position:absolute;top:0;left:0;transform:matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 40, 0, 1);width:1020px;height:100px;">  
  <div class="title">Title-1</div>
</div>
```

 So Visually, you might see on a page:
   Title-1
   Title-2
   Title-3
 
and the dom order will be same as visually the first time ember-collection renders and lays the elements out.

Then after doing a few sorts, rerenders .. etc .. you go back to original sort and see:

   Title-1
   Title-2
   Title-3

but when you look at the dom you see the elements are in this order:

  Title-2
  Title-3
  Title-1

so doing a query like:  $('.title') .. to test .. do I have the right order on my titles?  will not work. 

I think this is a puzzler of epic proportions ...

**Comment by raytiley** [comment]
Ember collection uses some test helpers currently to do this. I would start there.

https://github.com/emberjs/ember-collection/blob/master/tests/helpers/helpers.js

**Comment by danielspaniel** [comment]
Holy cow .. those are some fancy a-- test helpers .. that is my ticket to happiness. thanks :)
