### ISSUE TITLE
Ncaught Error: Assertion Failed: A helper named ‘percentage-columns-layout’ could not be found

### ISSUE THREAD

**Issue by bloodknight2010** [emberjs/ember-collection#118]
I installed the ember-collection addon. While the running my app I got the following error.
 **"Uncaught Error: Assertion Failed: A helper named 'percentage-columns-layout' could not be found"** 
What should I do? 
Pls help me.

Regards

Knight

**Comment by jeremytm** [comment]
I'm seeing the same thing. Ember 2.5.1. Ember-collection alpha 5.

**Comment by bloodknight2010** [comment]
Yes. Sure. I found the solution. Thank for your suggestion.

**Comment by jeremytm** [comment]
@bloodknight2010, would you mind sharing your solution?

**Comment by bloodknight2010** [comment]
I created percentage-columns-layout.js in helper and write the following codes

```
import Ember from 'ember';

export function percentageColumnsLayout(params/*, hash*/) {
  // return params;
     return {
    /**
     * Return an object that describes the size of the content area
     */
      contentSize(clientWidth, clientHeight) {
          return { params};
      }
    }
}

export default Ember.Helper.helper(percentageColumnsLayout);

```
