### ISSUE TITLE
requestAnimationFrame cycle runs forever

### ISSUE THREAD

**Issue by mmun** [emberjs/ember-collection#12]
Currently, the requestAnimationFrame cycle will never be broken. We should break the cycle (i.e. "cancel" the callback) in `willDestroyElement`.

See here: https://github.com/emberjs/ember-collection/blob/8bd9cc34304f26a7c2352e5e85db0731907555f5/addon/components/ember-collection.js#L125-L126.

**Comment by raytiley** [comment]
working on this now.
