### ISSUE TITLE
Fill gaps in Mixed Grid Layout

### ISSUE THREAD

**Issue by NicholasJohn16** [emberjs/ember-collection#134]
I have a collection of images that are all standard sizes (all widths or heights are 128, 256, or 512). I'm trying to use the mixed grid layout, but I want all the empty spaces to be filled. Is there anyway to do that by default or will I need to create a new layout or bin?

**Comment by stefanpenner** [comment]
@NicholasJohn16 I assuming you would like some sort of masonry grid? At this point, this is not supported out of the box. Although a new layout may be able to support this, if it does not. It would be interesting to explore what would be needed to support that use-case.

**Comment by NicholasJohn16** [comment]
Yup, masonry grid was what I was thinking of. Thanks for your help.

**Comment by stefanpenner** [comment]
@NicholasJohn16 I always wanted to implement masonry for this project, but never had the chance/opportunity.  Would love to see it added 👍
