### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by raytiley** [emberjs/ember-collection#14]
After leaving the dummy app open for a while I'm pretty sure the `requestAnimationFrame` is leaking memory somewhere. I'll take a look soon, just wanted to write this down so its being tracked.

<img width="1388" alt="simple 2015-08-18 18-23-31" src="https://cloud.githubusercontent.com/assets/41680/9344399/6523c23e-45d6-11e5-8cbb-590af6279526.png">

**Comment by stefanpenner** [comment]
likely related https://github.com/emberjs/ember-collection/issues/12

**Comment by raytiley** [comment]
> very much the source of at least one leak #12

Working on fixing that now... not sure this leak is the same though. I wasn't switching routes or anything, so the component was only rendered once, and just sat there leaking.

**Comment by stefanpenner** [comment]
> Working on fixing that now... not sure this leak is the same though. I wasn't switching routes or anything, so the component was only rendered once, and just sat there leaking.

ya, then we have atleast another

**Comment by lukemelia** [comment]
Still seems to be an issue after latest changes.

**Comment by krisselden** [comment]
When there is no GC pressure, the line will not come down in that view. In the current master version, after diffing snapshots, I could not reproduce a leak in requestAnimationFrame.
