### ISSUE TITLE
didInitAttrs and Ember.k DEPRECATION warnings for ember 2.13.1

### ISSUE THREAD

**Issue by nsharrok** [emberjs/ember-collection#150]
DEPRECATION: [DEPRECATED] didInitAttrs called in <mrx@component:ember-collection::ember1044>. [deprecation id: ember-views.did-init-attrs] See http://emberjs.com/deprecations/v2.x#toc_ember-component-didinitattrs for more details.

ember-collection/addon/components/ember-collection.js 
line 51    didInitAttrs() {

As a workaround hack I commented out lines 49 and 51

DEPRECATION: Ember.K is deprecated in favor of defining a function inline. [deprecation id: ember-metal.ember-k] See http://emberjs.com/deprecations/v2.x#toc_code-ember-k-code for more details.

ember-collection/addon/components/ember-collection.js 
line 85           willChange: Ember.K,
line 95           willChange: Ember.K,
As a workaround hack I replaced lines 85 ans 95 with willChange: this,

can you fix please?

**Comment by NickChristensen** [comment]
Looks like `ember-metal.ember-k` was fixed with #136, but there hasn't been a release since.

**Comment by Alonski** [comment]
There is a release on NPM 1.0.0-alpha.8.
You need to specify that when installing: yarn add ember-collection@1.0.0-alpha.8

This can be closed
