### ISSUE TITLE
Publish v1.0.0-alpha.8 to NPM Repository

### ISSUE THREAD

**Issue by Alonski** [emberjs/ember-collection#168]
Currently the latest NPM Ember Collection package is using v1.0.0-alpha.7.

The newest version fixes Ember.K and didInitAttrs depercations.

Currently I am importing this package like this: 
`"ember-collection": "https://github.com/emberjs/ember-collection",`

**Comment by thomblake** [comment]
npm currently has 1.0.0-alpha.8 - you can install it directly using `npm install ember-collection@1.0.0-alpha.8`

the website says latest is 1.0.0-alpha.7 so I'm guessing that one is tagged as 'latest'? Though I'm not entirely sure how that tagging works on npm. https://www.npmjs.com/package/ember-collection

**Comment by jacobq** [comment]
npm [`dist-tags`](https://docs.npmjs.com/cli/dist-tag) are separate from [`git tag`](https://git-scm.com/book/en/v2/Git-Basics-Tagging)s. It looks like what happened is that the last time it was published, the publisher used `npm publish --tag=alpha`. I believe `latest` can be updated by running `npm dist-tag add ember-collection@1.0.0-alpha.8 latest`

```
$ npm info ember-collection versions
 
[ '1.0.0-alpha.1',
  '1.0.0-alpha.2',
  '1.0.0-alpha.3',
  '1.0.0-alpha.4',
  '1.0.0-alpha.5',
  '1.0.0-alpha.6',
  '1.0.0-alpha.7',
  '1.0.0-alpha.8' ]
```

```
$ npm info ember-collection dist-tags
{ latest: '1.0.0-alpha.7', alpha: '1.0.0-alpha.8' }
```

**Comment by jacobq** [comment]
@Alonski your version specification should be [equivalent to specifying `master`](https://docs.npmjs.com/files/package.json#urls-as-dependencies), which is currently (as of 1/16/18) identical to `1.0.0-alpha.8`. If you switch it to `1.0.0-alpha.8` does anything change?

**Comment by Alonski** [comment]
Thanks @jacobq and @thomblake! I didn't realize that alpha8 was published :smile:
This works for me now
