### ISSUE TITLE
Publish alpha 8

### ISSUE THREAD

**Issue by alexlafroscia** [emberjs/ember-collection#171]
It seems like `alpha.8` was tagged but never published to NPM. Would you mind doing that? Thanks!

**Comment by stefanpenner** [comment]
1.0.0-alpha.8. looks published

**Comment by alexlafroscia** [comment]
Weird, I did `ember install ember-collection` and it didn't bump my local version to `alpha.8`...

**Comment by stefanpenner** [comment]
in general, alpa releases being latest is strange. @krisselden / @rwjblue any reason to not just release 1.0.0?
