### ISSUE TITLE
Some tests fail in Safari

### ISSUE THREAD

**Issue by mmun** [emberjs/ember-collection#19]
@shaunc has fixed it in https://github.com/shaunc/ember-collection/commit/5d2a9107b70e85e5fcb17ba11cdfb1b67e05fcbf so we need to cherry-pick / review the fix.

The issue, via @shaunc, is

> The problem is that if you set scrollTop to an impossible value and then resize to make it possible or closer to possible, browsers react in different ways.

**Comment by shaunc** [comment]
https://github.com/emberjs/ember-collection/pull/24
