### ISSUE TITLE
test tooling (phantomjs support?)

### ISSUE THREAD

**Issue by shaunc** [emberjs/ember-collection#43]
The fact that `ember-collection` doesn't run in phantomjs tripped me up for a time; at the least the documentation should mention that, as phantomjs is standard config for ember-cli apps.

Better would be to get it to work in phantomjs, though; we need a `requestAnimationFrame` polyfill. I tried https://github.com/cagosta/requestAnimationFrame but couldn't get it to work. Any ideas?

**Comment by calderas** [comment]
I ran into this issue and was able to use this polyfill for phantomjs
https://gist.github.com/paulirish/1579671

**Comment by shaunc** [comment]
ah great :)

**Comment by oliverwilkie** [comment]
If it helps, I installed this polyfill

`bower install raf.js`

and then updated my `ember-cli-build.js`

with 

```
  /**
   * phantomJS needs a polyfill of requestAnimationFrame, which
   * is used in ember-collection.
   */
   app.import('bower_components/raf.js/raf.min.js', {test: true});
```
