### ISSUE TITLE
build

### ISSUE THREAD

**Issue by analysisi** [emberjs/ember-collection#45]
hello,
i want use it ,but my web don't work on ember-cli, i use requirejs ,
can't you help to build like this link , thanks
https://rawgit.com/rondale-sc/list-view-dist/canary/list-view.js

**Comment by lukemelia** [comment]
Open to a PR that sets this up. Otherwise this is not a priority until
after ember-collection is in official release.

**Comment by analysisi** [comment]
ok,i see, thanks
