### ISSUE TITLE
ember-collection doesn't support Ember arrays

### ISSUE THREAD

**Issue by FezVrasta** [emberjs/ember-collection#55]
I fetch a list of ingredients using this computed property:

    results: Ember.computed('searchQuery', function() {
      return this.store.query('ingredient', { filter: searchQuery, limit: 150 });
    }

Then I can iterate trough the `results` using:

    {{#each results as |result|}}
      {{result.name}}
    {{/each}}

------

Now I'd like to use `{{ember-collection}}` but when I try to use it as follow: (it's basically the example on the readme of the component)

    {{#ember-collection
      items=results
      height=500
      width=800
      cell-layout=(fixed-grid-layout 800 50) as |item index|
    }}
      {{name}}
    {{/ember-collection}}

the ember-collection component displays just an empty list.

What am I doing wrong?

**Comment by mmun** [comment]
It is a bug in ember-collection. It doesn't support Ember's array yet, only natives one. It will be fixed eventually.

**Comment by FezVrasta** [comment]
Ok thanks, I have fixed it converting it with .toArray(), very annoying :(

**Comment by stefanpenner** [comment]
can your provide a quick demo app, that way i can quickly see whats wrong.
