### ISSUE TITLE
use main view as "scrolling container" instead of adding another child view

### ISSUE THREAD

**Issue by FezVrasta** [emberjs/ember-collection#56]
Corrently the main view of this component is useless, inside it there is a child view with `position: absolute` and `overflow: auto` and inside it there is the real list.

You may use the main view instead of creating the first child view, in this way we'd have less useless markup.

**Comment by krisselden** [comment]
The 'main' view is intended to be a higher level abstraction that is composing lower level components, there is more in this direction coming.  Some grid layouts like a spreadsheet style will have more than one scrollable and this composing container will just be a container.  I'm not sure what the concern is about the extra div tag but I'm going to close this for now as I feel like this isn't a real issue.
