### ISSUE TITLE
Remember scroll position

### ISSUE THREAD

**Issue by NicholasJohn16** [emberjs/ember-collection#60]
Is there an easy way to remember last scroll position after transitioning back into a route that uses this component?

**Comment by kaiwah** [comment]
+1, looking for a solution to this other than storing scroll state on every transition

**Comment by raytiley** [comment]
You can do this by binding `scroll-top` and / or `scroll-left` to properties in your controller. For example adding this line: `queryParams: ['scrollTop'],` to this controller in the dummy app (https://github.com/emberjs/ember-collection/blob/master/tests/dummy/app/controllers/scroll-position.js) will put the scroll position in the URL and will be remembered when you re-visit the route.

**Comment by lukemelia** [comment]
The scroll position is remembered even without the query param (though not across page reloads). I added a note to that page of the dummy app about this.
