### ISSUE TITLE
Nested data structure support?

### ISSUE THREAD

**Issue by matthewnessworthy** [emberjs/ember-collection#67]
Is it possible to create/render nested components/data structures with this component?

**Comment by krisselden** [comment]
I'm not a 100% clear on the question but if you are asking can this render a tree structure vs a list?  You need to flatten the tree structure into a list then you can use the component helper to vary on the node.type `{{#ember-collection items=flattenedTree as |node|}}{{component node.type item=node}}{{/ember-collection}}`.

**Comment by stefanpenner** [comment]
@krisselden I believe he is asking if you can have nested view tree, not tree data.

**Comment by Geokoumpa** [comment]
I recently came across a situation where a tree structure had to be rendered, with the root element count being 2k+. 

What I eventually did was calculate for each node its selfAndDescendants count recursively, also taking into consideration if each node's collapse button has been clicked. Then based on the selfAndDescendants counts of each root node, a computed property calculated all the itemSizes to be used with mixed-grid-layout.
