### ISSUE TITLE
Weird rendering glitch only in safari

### ISSUE THREAD

**Issue by caseyjenks** [emberjs/ember-collection#68]
Screencast showing it here: http://quick.as/o5pfqjqq

This only started happening after implementing ember-collection.

Any ideas? I'm not a CSS guy :-/

**Comment by caseyjenks** [comment]
Screenshot:

![playing_0_06___0_21](https://cloud.githubusercontent.com/assets/300131/10439430/d4a02394-7107-11e5-98e2-f924f22d8217.jpg)

**Comment by krisselden** [comment]
I need reproduction steps or a working demo.

**Comment by raytiley** [comment]
I pinged @caseyjenks in slack and he was unable to provide a reproduction. Going to close this for now. If someone is able to provide reproduction or more specific steps to cause this issue will reopen.
