### ISSUE TITLE
listening to scroll change 

### ISSUE THREAD

**Issue by danielspaniel** [emberjs/ember-collection#69]
I am trying to listen to the scrolling as the collection scrolls, and first thought of passing in 
my own scroll-change action to handle this, but that means the collection is actually delegating to 
my scroll change action instead of doing its own scrolly things. 

In the ember-collections component there is the action: 

```
  actions: {
    scrollChange(scrollLeft, scrollTop) {
      if (this._scrollChange) {
          this.sendAction('scroll-change', scrollLeft, scrollTop);
      } else {
        if (scrollLeft !== this._scrollLeft ||
            scrollTop !== this._scrollTop) {
          set(this, '_scrollLeft', scrollLeft);
          set(this, '_scrollTop', scrollTop);
          needsRevalidate(this);
        }
      }
    },
```
which means that if I pass in an action handler to listen for the scroll events ( custom action )  I am essentially overriding the components behavior. 

I am only interested in listening to scroll change events in a collection, so I am curious if there is a way to do that in a more elegant way, or a way that works, since my way not working?  I know I can attach a 'scroll' listener to the collection's div and use jquery to listen that way, but its not as fun. 

 Seems like I should be able to pass in my action handler and not override the original.  I don't mind submitting a PR for this if needed.

**Comment by alexander-alvarez** [comment]
If you extend the component, you should be able to call `_super` within your action handler to also call the original action.

```
actions: {
    scrollChange(scrollLeft, scrollTop) {
      // your code
     ...
      this._super(scrollLeft, scrollTop)
    }
}
```

**Comment by danielspaniel** [comment]
your right @alexander-alvarez, I could just do that .. I guess I was trying to fish about to see if the intent really was to have the passed in scroll-change listener override the built in one.  
 Not sure why that was done that way in other words.

**Comment by lukemelia** [comment]
@danielspaniel The idea was that the default behavior of scrolling should be that it works normally, BUT if you want to handle the scrollChange action in a true data down, actions up manner than we don't want to get in your way of updating the scrollLeft and scrollTop as you see fit.

Maybe too confusing? Definitely needs docs if it's going to stay like this.
