### ISSUE TITLE
fixed-grid.js:74 Uncaught TypeError: height depends on the first argument of visibleWidth(number)

### ISSUE THREAD

**Issue by haggins** [emberjs/ember-collection#71]
Hi,

I'm trying to get the sample running with alpha 4 but always get the error:

fixed-grid.js:74 Uncaught TypeError: height depends on the first argument of visibleWidth(number)

It seems like the component action `clientSizeChange(clientSize)` always gets only a number (width) as parameter instead of the expected `{width: xy; height: xy}` object.

My code is this:

template.hbs
```html
<div class="row" style="height: 500px;">
  <div class="col-md-12" style="height: 100%; position: relative;">
    {{#ember-collection height=500 width=800 items=model cell-layout=(fixed-grid-layout 800 50) as |item index|}}
      {{item.name}}
    {{/ember-collection}}
  </div>
</div>
```

route.js
```javascript
import Ember from 'ember';

export default Ember.Route.extend({
  model: function() {
    var items = [];
    for (var i = 0; i < 10000; i++) {
      items.push({name: "Item " + i});
    }
    return items;
  }
});
```
DEBUG: Ember      : 1.13.7
DEBUG: Ember Data : 1.13.8
DEBUG: jQuery     : 1.11.3

Edit: Updated my application but still get the same error
DEBUG: Ember      : 2.2.0
DEBUG: Ember Data : 2.2.1
DEBUG: jQuery     : 1.11.3

Are you able to reproduce this or did I forget something?

**Comment by raytiley** [comment]
@haggins could you create a new ember project with a bare bones recreation? I would like to take a stab at fixing, but haven't seen this issue in my tests / app.

**Comment by raytiley** [comment]
@haggins i'm going to close this... If your able to provide a reproduction please reopen. Thanks.
