### ISSUE TITLE
Could not find addon with name: ember-collection

### ISSUE THREAD

**Issue by sir-dunxalot** [emberjs/ember-collection#93]
Everytime I run `ember install ember-collection` I get the following error message. I find it hard to believe this bug is caused by this addon. However, I have not been able to reproduce this issue with any other ember addons.

![image](https://cloud.githubusercontent.com/assets/4495352/12772269/ca016d04-c9fd-11e5-8ec9-475b0b8226c4.png)

As you can see, `npm install --save-dev ember-collection` correctly installs the addon.

Again, I do not know if there is anything that can be fixed here as it's very isolated and very odd. However, I figured I'd let you know all the same.

Thanks for the great addon!

**Comment by sarus** [comment]
Interesting I just ran into this same issue.

Tried to do

```
ember install ember-collection
```
and got:

```
Install failed. Could not find addon with name: ember-collection
```

**Comment by Jordan4jc** [comment]
Yep I'm getting this issue as well.

**Comment by raytiley** [comment]
If I had to guess this is because `ember-cli` won't discover pre-release addons. I scanned the issues but didn't see one for this. I'll check in slack and see if anyone has an opinion.

**Comment by raytiley** [comment]
Hey everyone. This should be fixed now. Turns out there was a `0.0.0` version published to npm which shouldn't of been there. Thanks @rwjblue for getting rid of that for us.

![foo -zsh 82x24 2016-02-08 20-56-51](https://cloud.githubusercontent.com/assets/41680/12905602/85d6588a-cea6-11e5-8b02-a5809d58ff22.png)

**Comment by rwjblue** [comment]
Awesome job tracking that down @raytiley!  I'm going to close this (happy to reopen if needed later)...
